### ISSUE TITLE
there is a bug in example_2d.py

### ISSUE THREAD

**Issue by beibeichen01** [umbrellagong/VHGPR#1]
when i run the example_2d.py,i have the indexerror in the last cell,as descirbed in the picture.thank u very much.
<img width="731" alt="屏幕截图 2024-05-12 163221" src="https://github.com/umbrellagong/VHGPR/assets/91249107/4db58b70-85b0-41d9-8df6-1d0717f62fa7">
<img width="518" alt="屏幕截图 2024-05-12 163247" src="https://github.com/umbrellagong/VHGPR/assets/91249107/c7160129-1de6-43e7-9632-756d810727df">

**Comment by umbrellagong** [comment]
Hi,

Thanks for your comments. I ran the notebook again and did not see your issue. My matplotlib version is '3.3.4'. You can try to change to that version. If it does not work, just comment that line. It only adds a legend. 

Xianliang
